apiVersion: v1
kind: Service
metadata:
  name: travel-activity-service
  namespace: wanderly
spec:
  selector:
    app: travel-activity
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
