apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-activity
  namespace: wanderly
  labels:
    app: travel-activity
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-activity
  template:
    metadata:
      labels:
        app: travel-activity
    spec:
      containers:
        - name: travel-activity
          image: brendow21/travel-activity:latest
          ports:
            - containerPort: 8000
          env:
            - name: DJANGO_SETTINGS_MODULE
              value: travel_activity.settings
            - name: PYTHONUNBUFFERED
              value: "1"
          command: ["/bin/sh"]
          args:
            - "-c"
            - |
              ulimit -n 1048576
              exec gunicorn --bind 0.0.0.0:8000 travel_activity.wsgi:application
          resources:
            limits:
              cpu: "500m"
              memory: "512Mi"
            requests:
              cpu: "250m"
              memory: "256Mi"
      restartPolicy: Always
