apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-activity
  namespace: wanderly
spec:
  replicas: 1
  selector:
    matchLabels:
      app: travel-activity
  template:
    metadata:
      labels:
        app: travel-activity
    spec:
      securityContext:
        sysctls:
          - name: fs.inotify.max_user_watches
            value: "1048576"
      containers:
      - name: travel-activity
        image: brendow21/travel-activity:latest
        ports:
        - containerPort: 8000
        env:
        - name: DJANGO_SETTINGS_MODULE
          value: travel_activity.settings
        - name: PYTHONPATH
          value: /app/travel_activity/src
        - name: DJANGO_AUTORELOAD
          value: "0"
        - name: PYTHONUNBUFFERED
          value: "1"
        command: ["/app/start.sh"]
